resources:
  Resources:
    ${name}Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${name}-${id}
    escapinFunctionRole:
      Properties:
        Policies:
          - PolicyName: ${name}-${id}-FullAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "s3:ListAllMyBuckets"
                    - "s3:GetBucketLocation"
                  Resource: "*"
                - Effect: Allow
                  Action: "s3:*"
                  Resource:
                    "Fn::GetAtt":
                      - ${name}Bucket
                      - Arn
