resources:
  Resources:
    ${name}:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${name}
    escapinFunctionRole:
      Policies:
        - PolicyName: ${name}-FullAccess
          PolicyDocument:
            Version: '2017'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:ListAllMyBuckets'
                  - 's3:GetBucketLocation'
                Resource: '*'
              - Effect: Allow
                Action: 's3:*'
                Resource:
                  - 'Fn::GetAtt: [${name}, Arn]'
