swagger: "2.0"
info:
  title: mailgun API
  description: a subset of mailgun API
  version: "1.0.0"
schemes:
  - https
host: api.mailgun.net
basePath: /v3
security:
  - basicAuth: []
paths:
  "/{domain}/messages":
    parameters:
      - name: domain
        description: domain
        type: string
        in: path
      - name: key
    post:
      consumes:
        - multipart/form-data
        - application/x-www-form-urlencoded
      parameters:
        - name: from
          type: string
          in: formData
          required: true
        - name: to
          type: string
          in: formData
          required: true
        - name: subject
          type: string
          in: formData
        - name: text
          type: string
          in: formData
      responses:
        "200":
          schema:
            $ref: "#/responses/Succeeded"
        "400":
          schema:
            $ref: "#/responses/Error"
        "401":
          schema:
            $ref: "#/responses/Error"
        "402":
          schema:
            $ref: "#/responses/Error"
        "404":
          schema:
            $ref: "#/responses/Error"
        "500":
          schema:
            $ref: "#/responses/Error"
        "502":
          schema:
            $ref: "#/responses/Error"
        "503":
          schema:
            $ref: "#/responses/Error"
        "504":
          schema:
            $ref: "#/responses/Error"
responses:
  Succeeded:
    schema:
      $ref: "#/definitions/Message"
  Error:
    schema:
      $ref: "#/definitions/ErrorMessage"
definitions:
  Message:
    type: object
    required:
      - message
    properties:
      message:
        type: string
    example:
      message: "メッセージ"
  ErrorMessage:
    type: object
    required:
      - error_code
      - message
    properties:
      error_code:
        type: string
      message:
        type: string
    example:
      error_code: "エラーコード"
      message: "エラーの説明"
securityDefinitions:
  basicAuth:
    type: basic
