---
swagger: "2.0"
info:
  description: "sendmail"
  version: "1.0.0"
  title: "sendmail"
host: "sendmail.org"
basePath: "/v1"
schemes:
  - "http"
produces:
  - "application/json"
paths:
  /csv:
    get:
      summary: "Get a list of CSV files"
      description: "Get a list of CSV files"
      x-escapin-handler: "instance.csvGET"
      parameters: []
      responses:
        200:
          description: "A list of CSV files"
          schema:
            $ref: "#/definitions/List"
    post:
      summary: "Upload CSV file"
      description: "Upload CSV file for sending emails"
      x-escapin-handler: "instance.csvPOST"
      consumes:
        - "application/x-www-form-urlencoded"
      parameters:
        - name: "csv"
          in: "formData"
          description: "A csv file"
          required: true
          type: "file"
      responses:
        201:
          description: "Resource Created"
          schema:
            $ref: "#/definitions/Id"
          headers:
            Location:
              type: "string"
              format: "uri"
              description: "URI to be assigned a new resource"
        400:
          description: "Illegal Argument"
          schema:
            $ref: "#/definitions/ErrorMessage"
        default:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ErrorMessage"
  /csv/{id}:
    get:
      summary: "Download CSV file"
      description: "Download CSV file by id"
      x-escapin-handler: "instance.csvIdGET"
      produces:
        - "text/csv"
      parameters:
        - name: "id"
          in: "path"
          description: "id of a CSV file"
          required: true
          type: "string"
      responses:
        200:
          description: "CSV file"
        404:
          description: "Resource Not Found"
          schema:
            $ref: "#/definitions/ErrorMessage"
        default:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ErrorMessage"
    delete:
      summary: "Delete CSV file"
      description: "Delete CSV file by id"
      x-escapin-handler: "instance.csvIdDELETE"
      parameters:
        - name: "id"
          in: "path"
          description: "id of a CSV file"
          required: true
          type: "string"
      responses:
        200:
          description: "Succeeded"
          schema:
            $ref: "#/definitions/Message"
        404:
          description: "Resource Not Found"
          schema:
            $ref: "#/definitions/ErrorMessage"
        default:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ErrorMessage"
definitions:
  Id:
    type: "object"
    required:
      - "id"
    properties:
      id:
        type: "string"
    example:
      id: "1234"
  Message:
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"
    example:
      message: "メッセージ"
  ErrorMessage:
    type: "object"
    required:
      - "error_code"
      - "message"
    properties:
      error_code:
        type: "string"
      message:
        type: "string"
    example:
      error_code: "エラーコード"
      message: "エラーの説明"
  List:
    type: "array"
    items:
      $ref: "#/definitions/Id"
responses:
  Succeeded:
    description: "Succeeded"
    schema:
      $ref: "#/definitions/Message"
  Created:
    description: "Resource Created"
    schema:
      $ref: "#/definitions/Id"
    headers:
      Location:
        type: "string"
        format: "uri"
        description: "URI to be assigned a new resource"
  IllegalArgument:
    description: "Illegal Argument"
    schema:
      $ref: "#/definitions/ErrorMessage"
  NotFound:
    description: "Resource Not Found"
    schema:
      $ref: "#/definitions/ErrorMessage"
  ServerError:
    description: "Server Error"
    schema:
      $ref: "#/definitions/ErrorMessage"
