service: ${name}
provider:
  name: ${platform}
  runtime: ${runtime}
  stage: ${stage}
functions:
resources:
  Resources:
    escapinFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /escapin/
        RoleName: ${name}EscapinFunctionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
