name: merge master into develop

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: merge master into develop
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          stable_branch: master
          development_branch: develop
          allow_ff: false
          user_name: escapinbot
          user_email: kimusaku+escapinbot@gmail.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
