name: Node.js Package

on:
  push:
    tags: v*

jobs:
  publish-yarn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.yarnpkg.com/
      - run: |
          yarn
          yarn prettier-check
          yarn lint
          yarn test
          yarn build
          yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
