name: pull request

on:
  pull_request:

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and test
        run: npm install-ci-test
      - name: build
        run: npm run build
